### ISSUE TITLE
Stuck on "INFO: Connection successful"

### ISSUE THREAD

**Issue by yanpeng7** [abr/abr_jaco2#24]
I followed the steps in #23 and installed kinova SDK on Ubuntu 20.04, and I was able to control the robot via the SDK GUI. However, when I ran `control_loop_speed_test.py `, I got the following output and is stuck on `INFO: Connection successful`, and I have to close the terminal window to terminate it(ctrl+c won't do anything). The segmentation fault never happens. Update: After of poking around, I found that the code gets stuck on `interface.init_position_mode()`. I did some tracing, it seems like it could not execute past `self.jaco2.InitPositionMode()` in interface.py
```
Generating Jacobian function for EE[0,0,0]_J
Generating transform function for EE[0,0,0]_Tx
Generating inertia matrix function
Generating Jacobian function for link0[0,0,0]_J
Generating transform function for link0[0,0,0]_Tx
Generating Jacobian function for link1[0,0,0]_J
Generating transform function for link1[0,0,0]_Tx
Generating Jacobian function for link2[0,0,0]_J
Generating transform function for link2[0,0,0]_Tx
Generating Jacobian function for link3[0,0,0]_J
Generating transform function for link3[0,0,0]_Tx
Generating Jacobian function for link4[0,0,0]_J
Generating transform function for link4[0,0,0]_Tx
Generating Jacobian function for link5[0,0,0]_J
Generating transform function for link5[0,0,0]_Tx
Generating Jacobian function for link6[0,0,0]_J
Generating transform function for link6[0,0,0]_Tx
Generating Jacobian function for joint0[0,0,0]_J
Generating transform function for joint0[0,0,0]_Tx
Generating Jacobian function for joint1[0,0,0]_J
Generating transform function for joint1[0,0,0]_Tx
Generating Jacobian function for joint2[0,0,0]_J
Generating transform function for joint2[0,0,0]_Tx
Generating Jacobian function for joint3[0,0,0]_J
Generating transform function for joint3[0,0,0]_Tx
Generating Jacobian function for joint4[0,0,0]_J
Generating transform function for joint4[0,0,0]_Tx
Generating Jacobian function for joint5[0,0,0]_J
Generating transform function for joint5[0,0,0]_Tx
Loading expression from EE[0,0,0]_Tx ...
Generating gravity compensation function
Loading expression from link0[0,0,0]_J ...
Loading expression from link1[0,0,0]_J ...
Loading expression from link2[0,0,0]_J ...
Loading expression from link3[0,0,0]_J ...
Loading expression from link4[0,0,0]_J ...
Loading expression from link5[0,0,0]_J ...
Loading expression from link6[0,0,0]_J ...
Loading expression from joint0[0,0,0]_J ...
Loading expression from joint1[0,0,0]_J ...
Loading expression from joint2[0,0,0]_J ...
Loading expression from joint3[0,0,0]_J ...
Loading expression from joint4[0,0,0]_J ...
Loading expression from joint5[0,0,0]_J ...
Using Force Command 0x200: 512
INFO: RS485 initialization completed
INFO: Activating Jaco2...
INFO: Connection successful
```
Then, if I run 
After this if I run `reaching_osc.py` , it gets stuck on INFO: Connection successful. The same happens if I try to rerun `control_loop_speed_test.py `.
```
Using Force Command 0x200: 512
INFO: RS485 initialization completed
INFO: Activating Jaco2...
INFO: Connection successful
```
If I rerun `connection_test.py` however, everything works and exits properly.

Do you know what could be happening? Thanks a lot in advance!

**Comment by p3jawors** [comment]
Hello @yanpeng7 ,

Thanks for checking out the repo. Can you send me a few more pieces of info and run another test? I'll need your pip list so I can see what versions you are using for the various packages. Can you also try running the joint space controller [here](https://github.com/abr/abr_jaco2/blob/master/examples/joint_space_position_control.py). This will omit the force control and show whether the communication with the jaco is working as expected.

Cheers,

Pawel

**Comment by yanpeng7** [comment]
Thank a lot for the quick response!
The follows is the output of my pip list`,
```
abr-control     0.1.0      /home/pingcheng/Desktop/second_try/abr_control
abr-jaco2       0.1.0.dev0 /home/pingcheng/Desktop/second_try/abr_jaco2  
certifi         2020.6.20  
chardet         4.0.0      
cloudpickle     1.6.0      
cycler          0.10.0    
Cython          0.29.24    
idna            2.10      
kiwisolver      1.1.0      
matplotlib      3.0.3      
mpmath          1.2.1      
nengo           3.1.0      
numpy           1.16.1    
pip             10.0.1    
pydmps          0.2        /home/pingcheng/Desktop/second_try/pydmps    
pyparsing       2.4.7      
python-dateutil 2.8.2      
requests        2.25.1    
scipy           1.4.1      
setuptools      50.3.2    
six             1.16.0    
sympy           1.6.2      
urllib3         1.26.7    
wheel           0.37.0    
```
And below is my `conda list`
```
# packages in environment at /home/pingcheng/anaconda3/envs/new_jaco2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
abr-control               0.1.0                     dev_0    <develop>
abr-jaco2                 0.1.0.dev0                dev_0    <develop>
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2020.6.20          pyhd3eb1b0_3  
chardet                   4.0.0                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.24                  pypi_0    pypi
idna                      2.10                     pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
matplotlib                3.0.3                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
nengo                     3.1.0                    pypi_0    pypi
numpy                     1.16.1                   pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
pip                       10.0.1                   py35_0  
pydmps                    0.2                       dev_0    <develop>
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.5.6                h12debd9_1  
python-dateutil           2.8.2                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.25.1                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                50.3.2                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
sympy                     1.6.2                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
urllib3                   1.26.7                   pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```
I tried running joint space controller but it seemed to get stuck at the exact same place, namely `interface.init_position_mode()`. Below is my output, and the code just gets stuck after `INFO: Connection successful`, and I can not terminate it using ctrl+c.
```
Using Force Command 0x200: 512
INFO: RS485 initialization completed
INFO: Activating Jaco2...
INFO: Connection successful
```
For reference, the computer I'm currently using has a Intel i5-1035G1 CPU1.00GHz.
Thanks again, I really appreciate your help!

**Comment by p3jawors** [comment]
Hmm, if you are able to control the arm through the Kinova  SDK GUI, then it may be that you are running a newer firmware on the arm. Can you check what firmware you have, you should be able to check through the same SDK GUI. I have been running my Jaco Gen 2 on 5.5.0.

**Comment by yanpeng7** [comment]
Hi Pawel,
I checked it and we are using 6.2.8. Should we try to downgrade the firmware? Also we have a 6 DOF arm, that should not be an issue right? Since it seems like 5.5.0 is on longer available on the website I will contact Kinova support to try to get it.
Thanks again.

**Comment by p3jawors** [comment]
Hi @yanpeng7 ,

I have only used this repo for the 6dof gen 2 arm, so that should be fine. Yes I think you'll have better luck downgrading to 5.5.0. Here's a [link](https://drive.google.com/file/d/1jtbnqhJRpX1rpE4qGhH2cDPzUWi3F4Az/view?usp=sharing) to the firmware I dug up from an old email you can try using. I do recommend you get a hold of customer support at Kinova for help with the firmware downgrade, to make sure you're following the right steps. It's been a few years since I've done it, so I don't remember all of the details.

Cheers

**Comment by yanpeng7** [comment]
Hello Pawel,
Unfortunately even after we upgraded the firmware to 5.5.0, the problem is exactly the same as before. Do you have other recommendation?
![firmware_version](https://user-images.githubusercontent.com/54511661/143721334-5fcb334c-af3d-4aa8-ba96-c5bb872793ef.png)
Thanks.

**Comment by p3jawors** [comment]
I noticed your cython version is slightly different from mine. You could try and make sure your environment matches this...
```(jaco) pjaworsk@ABR04:~$ pip list
Package         Version             Location
--------------- ------------------- ------------------------------
abr-control     0.1.0               /home/pjaworsk/src/abr_control
abr-jaco2       0.1.0.dev0          /home/pjaworsk/src/abr_jaco2
certifi         2020.12.5
chardet         4.0.0
cloudpickle     1.6.0
cycler          0.10.0
Cython          0.29.14
idna            2.10
kiwisolver      1.3.1
matplotlib      3.3.3
mpmath          1.1.0
numpy           1.19.5
Pillow          8.1.0
pip             20.3.3
pyparsing       2.4.7
python-dateutil 2.8.1
requests        2.25.1
scipy           1.5.4
setuptools      52.0.0.post20210125
six             1.15.0
sympy           1.7.1
urllib3         1.26.2
wheel           0.36.2
```
I just tested this on my jaco2 and it runs the [joint space example](https://github.com/abr/abr_jaco2/blob/master/examples/joint_space_position_control.py) I linked above fine. I recommend debugging with this example because it just connects and uses the onboard position controller. If that works fine then you can look into the force control options.

**Comment by yanpeng7** [comment]
Hi Pawel,
Thanks a lot for following through with this, I really appreciate it! I have updated Cython but that was not the cause as the error is still the same. After I enabled logging by setting `self.jaco2 = jaco2_rs485.pyJaco2(display_error_level=1, use_redis)`, the error is as follows. Hopefully the error can give you a better idea of what is going on. 
```
30-11-2021 01:20:33 DEBUG: Initializing RS-485 Communication...
30-11-2021 01:20:33 INFO: RS485 initialization completed
30-11-2021 01:20:33 INFO: Activating Jaco2...
30-11-2021 01:20:33 INFO: Connection successful
30-11-2021 01:20:33 DEBUG: Initializing position control mode...
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 0, Response: 65537
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 1, Response: 65537
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 2, Response: 1422196737
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 3, Response: 65537
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 4, Response: 65537
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 5, Response: 65537
30-11-2021 01:20:33 DEBUG: Data for joint 0 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 1 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 2 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 3 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 4 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 5 not updated, checking again...
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 0, Response: 2297823233
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 1, Response: 65537
30-11-2021 01:20:33 DEBUG: Switch control mode to Position control True for servo 2, Response: 1
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 3, Response: 65537
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 4, Response: 65537
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 5, Response: 65537
30-11-2021 01:20:33 DEBUG: Data for joint 0 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 1 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 3 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 4 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 5 not updated, checking again...
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 0, Response: 65537
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 1, Response: 65537
30-11-2021 01:20:33 DEBUG: Switch control mode to Position control True for servo 2, Response: 1
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 3, Response: 65537
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 4, Response: 65537
30-11-2021 01:20:33 DEBUG: No response to control mode switch request for servo 5, Response: 65537
30-11-2021 01:20:33 DEBUG: Data for joint 0 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 1 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 3 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 4 not updated, checking again...
30-11-2021 01:20:33 DEBUG: Data for joint 5 not updated, checking again...
```
Thanks again!

**Comment by p3jawors** [comment]
The only idea I have left is that you could try recompiling the interface code again to see if that works for you. Otherwise I think you'll have to contact the Kinova engineers for help, as I suspect this is something that may be unique to your system. I've had other users able to connect and use it directly from the pip install.

[Here is a link](https://drive.google.com/file/d/0B3Ygg12HPxfTeF9NQTVwdEt4b0k/view?usp=sharing&resourcekey=0-lThNX88ENVpt6KV-BSOzgg) to the API document from Kinova for the rs485 interface. It seems that you are able to connect, but are failing on message `0x0203` for `Switch Control Mode Request`. You are trying to switch into position mode, and the return message is giving a fail (`DATA0` of message `0x0204`).

One thing that comes to mind as I write this, it may be that your CPU isn't powerful enough to run this low level API. I recall there being various messages that require responses within some given time. For comparison, I am using an `AMD® Ryzen 9 3950x 16-core processor × 32, max 4.7GHZ`, but in the past I've used an `Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz`. If you have access to another, more powerful machine, I would recommend trying on there as well.

Let me know if you sort out / find an issue and I can update the repo.

Best of luck!

**Comment by p3jawors** [comment]
@yanpeng7 I pushed some changes to master and a newly compiled interface (.so in the interfaces folder). See if that helps with your issues.

**Comment by yanpeng7** [comment]
Thanks! I created a new python 3.8 environment and installed everything from scratch but when I ran `connection_test.py` it gave me this error, which is really weird since I never got it before on 3.5 and the names of files in interface folder didn't even change. 
```
Traceback (most recent call last):
  File "connection_test.py", line 3, in <module>
    import abr_jaco2
  File "/home/pingcheng/Desktop/abr_38/abr_jaco2/abr_jaco2/__init__.py", line 2, in <module>
    from .interface import jaco2_rs485
ImportError: cannot import name 'jaco2_rs485' from 'abr_jaco2.interface' (/home/pingcheng/Desktop/abr_38/abr_jaco2/abr_jaco2/interface/__init__.py)
```

**Comment by p3jawors** [comment]
Did you run `pip install -e .` from the root folder (the first `abr_jaco2` folder, not `abr_jaco2/abr_jaco2`), and are you running examples from the `examples` folder?

**Comment by yanpeng7** [comment]
I made sure to install from the root folder and this is the output of my `pip install -e .`
```
~/Desktop/abr_38/abr_jaco2$ pip install -e .
Obtaining file:///home/pingcheng/Desktop/abr_38/abr_jaco2
Requirement already satisfied: cython>=0.29.0 in /home/pingcheng/anaconda3/envs/jaco38/lib/python3.8/site-packages (from abr-jaco2==0.1.0.dev0) (0.29.14)
Requirement already satisfied: numpy>=1.16.0 in /home/pingcheng/anaconda3/envs/jaco38/lib/python3.8/site-packages (from abr-jaco2==0.1.0.dev0) (1.21.4)
Requirement already satisfied: setuptools>=18.0 in /home/pingcheng/anaconda3/envs/jaco38/lib/python3.8/site-packages (from abr-jaco2==0.1.0.dev0) (58.0.4)
Requirement already satisfied: cloudpickle>=0.8.0 in /home/pingcheng/anaconda3/envs/jaco38/lib/python3.8/site-packages (from abr-jaco2==0.1.0.dev0) (2.0.0)
Requirement already satisfied: sympy>=1.3 in /home/pingcheng/anaconda3/envs/jaco38/lib/python3.8/site-packages (from abr-jaco2==0.1.0.dev0) (1.7.1)
Requirement already satisfied: mpmath>=0.19 in /home/pingcheng/anaconda3/envs/jaco38/lib/python3.8/site-packages (from sympy>=1.3->abr-jaco2==0.1.0.dev0) (1.2.1)
Installing collected packages: abr-jaco2
  Running setup.py develop for abr-jaco2
Successfully installed abr-jaco2-0.1.0.dev0
```
I have also tried deleting `jaco2_cython.cpp` but it seems like the file is not regenerating from the `pip install -e .` command, could this have something to do with the problem? The error is still the same as last time. Thanks!

**Comment by p3jawors** [comment]
That is odd, I'll see if I can set aside some time to look into this, but it may be a little bit. In the mean time I would suggest copying the missing files from the repo and working from there.

**Comment by p3jawors** [comment]
@yanpeng7 you are correct, the last update to master had an issue in the setup.py. I've fixed that in the latest commit to master. Make sure to check the README as the install command is slightly different.

**Comment by yanpeng7** [comment]
Thanks a lot! I will try it as soon as I get the chance!

**Comment by p3jawors** [comment]
Closing due to inactivity.
